config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about' #get - для обработки других страниц.

  resources :posts do #создаем REST- архитектуру. Отслеживание URL адресов в нутри других URL адресов.
    resources :comments
  end   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments # has_many - имеет много
  validates :title,presence: true,length: {minimum:5} # 
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "adnin", password: "D282546D"
  #Разрешает просматривать незарегистрированым пользователям только  index и show!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @pages = 'Новый YogaBlog'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "D282546D", example: [:index, :show]
  #Разрешает просматривать незарегистрированым пользователям только  index и show!

  def index # Функция отвечающая на обработку главной страницы.
    @post = Post.all
  end

  def new
    @post = Post.new
  end  
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit # вызывается когда мы переходим на редактирование постов.
    @post = Post.find(params[:id])
  end

  def update #обновляем отредактированиые статьи.
    @post = Post.find(params[:id])

    if (@post.update(post_params)) #обновляется пост
      redirect_to @post
    else
      render 'edit' # возвращем на edit.
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end  
  
  def create
    @post = Post.new(post_params)
    
    if (@post.save)
      redirect_to @post
    else
      render 'new' # просто перезагружает страницу.
    end    
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YogaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">YogaBlog</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to "Главная страница", home_path %></span>
        <span class="p-2 text-dark"><%= link_to "О нас", about_path %></span>
      </nav>
      <span class="p-2 text-dark"><%= link_to "Добавления поста", new_post_path %></span>
    </div>
    <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @pages %></h4>

app/views/posts/edit.html.erb
<h2>Редактирование нового поста</h2>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg|%>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название <br>
    <%= f.text_field(:title, {:class => 'form-control'})%>
  </p>

  <p>
    Текст статьи <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  
  <p>
    <%= f.submit({:class => 'btn btn-success'})%>
  </p>  
<% end %>  

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post|%>
  <div class='well'>
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to 'Читать далее', post_path(post), :class => 'btn btn-primary' %>  
  </div>
  <br>
  <hr>
<% end %>  

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg|%>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название <br>
    <%= f.text_field(:title, {:class => 'form-control'})%>
  </p>

  <p>
    Текст статьи <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  
  <p>
    <%= f.submit({:class => 'btn btn-success'})%>
  </p>  
<% end %>  

app/views/posts/show.html.erb
<br>
<h1><%= @post.title%></h1>
<p><%= @post.body%></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить", post_path(@post), method: :delete, data:{confirm: "Хотите удалить статью"}, :class => 'btn btn-danger' %>
<br>
<hr>

<h2>Добавить коментарий</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Пользователь <br>
    <%= f.text_field(:username, {:class => 'form-control'})%>
  </p>

  <p>
    Текст коментария <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  
  <p>
    <%= f.submit("Добавить коментарий",{:class => 'btn btn-warning'})%>
  </p>  
<% end %>  

<h1>Все коментарии</h1>
<% @post.comments.each do |comment|%>
  <div class='alert alert-light'>
    <p><strong><%= comment.username %></strong>: <%= comment.body%></p>
  </div>
  <hr>
<% end %>  